[build]
  publish = "."

# Proxy del front a tu Apps Script (preserva la query ?p=...)
[[redirects]]
  from = "/api"
  to = "https://script.google.com/macros/s/AKfycbyfM0eSX32eqkfGgYpF66sc7I2NhHdP8qUw_ArRGsjZ9FpcZKIyhH3ReSOQKKRmGSUcpw/exec"
  status = 200
  force = true

# (Opcional) Cache básico para archivos estáticos
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"


   