[build]
  publish = "."

# Proxy del front a tu Apps Script (preserva la query ?p=...)
[[redirects]]
  from = "/api"
  to = "https://script.google.com/macros/s/AKfycbzEECdS2zqthpKKg0t4raZejFU-9HsJFSnh-Wck6Wlg_hiTR5PaEd-_5sWPADJp2srqxA/exec"
  status = 200
  force = true

# (Opcional) Cache básico para archivos estáticos
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"


   